name: lavaburst
dependencies:
- python=3.5
- numpy
- scipy
- cython
- matplotlib
- seaborn
- pandas
- six
- nose>=1.3
- pip>=7.1
- pip:
  - git+git://github.com/nezar-compbio/lavaburst.git
  - git+git://github.com/mirnylab/cooler.git
  - https://bitbucket.org/mirnylab/mirnylib/get/tip.tar.gz
